name: CI Ubuntu

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  schedule:
    - cron: "0 10 * * 0,3" # Runs every Sunday and Wednesday at 2:00 AM in Pacific Time

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false

      matrix:
        build_type: [Release, Debug]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: cmake freeglut3-dev
        version: 1.0

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DBUILD_WITH_BULLET=ON
        -DBUILD_PYTHON_BINDINGS=OFF
        -S ${{ github.workspace }}/src

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }} --parallel 4

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }}
